name: Test & Build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Test Race
      run: make race

    - name: Test Coverage 
      run: make coverage
            
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.0.2

    - name: Format Check
      run: |
        OUTPUT=$(make fmt)
        if [ -n "$OUTPUT" ]; then
          echo "gofmt detected changes:"
          echo "$OUTPUT"
          exit 1
        fi
